---
version: "3"
services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8281:8181/tcp
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /mnt/4tb/docker/tautulli/config:/config
