---
version: "3"
services:
  code-server:
    container_name: code-server
    hostname: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PASSWORD=${ACCESS_PASSWORD}
      - SUDO_PASSWORD=${ACCESS_PASSWORD}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - DEFAULT_WORKSPACE=/config/workspace
    image: linuxserver/code-server:latest
    network_mode: bridge
    ports:
      - 9443:8443/tcp
    restart: unless-stopped
    volumes:
      - /volume1/docker/code-server/config:/config
      - /volume1/docker:/mnt/docker
