---
version: "3"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /dev/dri:/dev/dri
      - /volume1/docker/plex/config:/config
      - /mnt/4tb/winshare/music:/music
      - /mnt/3tb/movies:/movies
      - /mnt/3tb/tvshow/:/tv
      - /mnt/3tb/DA/:/DA
