---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    hostname: komga
    network_mode: bridge
    volumes:
      - /mnt/4tb/winshare/Comics:/data
      - /mnt/4tb/winshare/Comics_Import:/import
      - /volume1/docker/komga/config:/config
      - /etc/timezone:/etc/timezone
    ports:
      - 5000:8080
    user: "1000:1000"
    restart: unless-stopped
