---
version: '3.3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9090:9090
    volumes:
        - '/data/docker/prometheus/data/prometheus.yml:/etc/prometheus/prometheus.yml'
