---
version: "3"
services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    hostname: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brusselss
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8112:8112/tcp
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /mnt/4tb/docker/deluge/config:/config
      - /mnt/4tb/docker/torrents/downloads:/downloads
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 7878:7878/tcp
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /mnt/4tb/docker/radarr/config:/config
      - /mnt/4tb/docker/torrents/downloads:/downloads
      - /mnt/3tb/movies:/movies/library
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /mnt/4tb/docker/sonarr/config:/config
      - /mnt/4tb/docker/torrents/downloads:/downloads
      - /mnt/3tb/tvshow:/tv/library
  lidarr:
    image: linuxserver/lidarr:latest
    hostname: lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8686:8686/tcp
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /mnt/4tb/docker/lidarr/config:/config
      - /mnt/4tb/docker/torrents/downloads:/downloads
      - /mnt/4tb/winshare/music:/music/library
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: Prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    network_mode: bridge
    ports:
      - 9696:9696/tcp
    restart: unless-stopped
    volumes:
      - /mnt/4tb/docker/prowlarr/config:/config
