version: "3"
services:
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    hostname: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8112:8112/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/deluge/config:/config
      - /data/volume1/docker/torrents/downloads:/downloads
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 7878:7878/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/radarr/config:/config
      - /data/volume1/docker/torrents/downloads:/downloads
      - /data/volume1/movies:/movies
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/sonarr/config:/config
      - /data/volume1/docker/torrents/downloads:/downloads
      - /data/volume1/tv:/tv
  mylar:
    image: linuxserver/mylar3:latest
    container_name: mylar
    hostname: mylar
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8090:8090/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/mylar3/config:/config
      - /data/volume1/docker/torrents/downloads:/downloads
      - /data/volume1/comics:/comics
  lidarr:
    image: linuxserver/lidarr:latest
    hostname: lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 8686:8686/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/lidarr/config:/config
      - /data/volume1/docker/torrents/downloads:/downloads
      - /data/volume1/music:/music
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: Prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 9696:9696/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/doc1ker/Prowlarr/config:/config