version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
#    network_mode: bridge
    ports:
      - 80:80
      - 443:443
      - 8180:8080
    environment:
      - CF_API_EMAIL=blacksadum@gmail.com
      - CF_DNS_API_TOKEN=ZfKqonfNF_G7aooXzqaTRfzXv-NYCTbtbxzit_J_
      # - CF_API_KEY=YOU_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/workplace/docker/traefik/traefik.yml:/traefik.yml:ro
      - /home/ubuntu/workplace/docker/traefik/acme.json:/acme.json
      - /home/ubuntu/workplace/docker/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.ekielzan.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=blacksad:$$apr1$$4SQ4..Lv$$cneES9WLY1ESPwCHYOf46/"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.ekielzan.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=ekielzan.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.ekielzan.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    command:
      - "--api=true"
      - "--metrics.prometheus=true"

networks:
  proxy:
    external: true
