version: "3"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - 3406:443/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/nextcloud/Config:/config
      - /datancl:/data