version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_NOTIFICATION_URL: "discord://6mGCOBiS5vPW9WnL5Uy5Pf6hEi1oaCLKyXKRQ3gBMDUwQWXTaPF3WW79ApfX5AAMqPnl@934214399240048700"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})':' {{.Message}}{{println}}{{end}}

      WATCHTOWER_NOTIFICATIONS: shoutrrr
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
