---
version: '3'
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    hostname: littlelinkserver
    environment:
      - META_TITLE=Gilles Dejeneffe
      - META_DESCRIPTION=Gilles Page
      - META_AUTHOR=Gilles Dejeneffe
      - THEME=Dark
      # - FAVICON_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_URL=https://media-exp1.licdn.com/dms/image/C4D03AQFLPirVH7_CbQ/profile-displayphoto-shrink_200_200/0/1645999892372?e=1651708800&v=beta&t=mirZFGiHP5HgDtEtz1RMjdK7TCxa7NAiyc-KAaVvynE
      # - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - AVATAR_ALT=Gilles Profile Pic
      - NAME=Gilles Dejeneffe
      - BIO=Internet veteran turned DevOps Ninja and SRE Samuraï. Aka Blacksad, EkielZan, Imarite
      - GITHUB=https://github.com/Ekielzan
      - TWITTER=https://twitter.com/Blacksadum
      - STEAM=https://steamcommunity.com/id/blacksadum/
      - REDDIT=https://www.reddit.com/user/imarite
      - LINKED_IN=https://www.linkedin.com/in/gilles-dejeneffe/
      # - INSTAGRAM=https://www.instagram.com/techno.tim
      # - YOUTUBE=https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
      # - TWITCH=https://www.twitch.tv/technotim/
      # - DISCORD=https://l.technotim.live/discord
      # - TIKTOK=https://www.tiktok.com/@technotim
      # - KIT=https://kit.co/TechnoTim
      # - FACEBOOK=https://facebook.com
      # - FACEBOOK_MESSENGER=https://facebook.com
      # - PRODUCT_HUNT=https://www.producthunt.com/
      # - SNAPCHAT=https://www.snapchat.com/
      # - SPOTIFY=https://www.spotify.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      # - EMAIL=you@example.com
      # - EMAIL_ALT=you@example.com
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TELEGRAM=https://telegram.org/
      # - TUMBLR=https://www.tumblr.com/
      # - VIMEO=https://vimeo.com/
      # - WORDPRESS=https://wordpress.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
      - FOOTER=No trees were killed to display this page, but a large number of electrons were terribly inconvenienced.
    ports:
      - 8083:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: bridge
