---
version: '3'
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    hostname: littlelinkserver
    environment:
      - META_TITLE=Gilles Dejeneffe
      - META_DESCRIPTION=Gilles Page
      - META_AUTHOR=Gilles Dejeneffe
      - THEME=Dark
      - AVATAR_URL=https://i.ibb.co/GFGpB76/1645999892372.jpg
      - AVATAR_ALT=Gilles Profile Pic
      - NAME=Gilles Dejeneffe
      - BIO=Internet veteran turned DevOps Ninja and SRE Samuraï. Aka Blacksad, EkielZan, Imarite
      - GITHUB=https://github.com/Ekielzan
      - TWITTER=https://twitter.com/Blacksadum
      - STEAM=https://steamcommunity.com/id/blacksadum/
      - REDDIT=https://www.reddit.com/user/imarite
      - LINKED_IN=https://www.linkedin.com/in/gilles-dejeneffe/
      - FOOTER=No trees were killed to display this page, but a large number of electrons were terribly inconvenienced.
    ports:
      - 8083:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.littelink.entrypoints=http"
      - "traefik.http.routers.littelink.rule=Host(`littelink.local.ekielzan.com`,`www.ekielzan.com`)"
      - "traefik.http.middlewares.littelink-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.littelink.middlewares=littelink-https-redirect"
      - "traefik.http.routers.littelink-secure.entrypoints=https"
      - "traefik.http.routers.littelink-secure.rule=Host(`littelink.local.ekielzan.com`,`www.ekielzan.com`,`ekielzan.com`)"
      - "traefik.http.routers.littelink-secure.tls=true"
      - "traefik.http.routers.littelink-secure.service=littelink"
      - "traefik.http.services.littelink.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
