version: '3.3'
services:
    wg-easy:
        container_name: wg-easy
        hostname: wg-easy
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - WG_HOST=vpn.ekielzan.com
            - PASSWORD=password
            - WG_DEFAULT_ADDRESS=192.168.69.x
            - WG_DEFAULT_DNS=192.168.68.105
        volumes:
            - /volume1/docker/wireguard-gui:/etc/wireguard
        ports:
            - '51820:51820/udp'
            - '51821:51821/tcp'
        restart: unless-stopped
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        image: weejewel/wg-easy
