version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/mariadb/config:/config
