---
version: "2.1"
services:
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /volume1/docker/mysql-workbench/config:/config
    ports:
      - 3200:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
