version: "3"
services:
  deluge:
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    hostname: deluge
    image: linuxserver/deluge:latest
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8112:8112/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/deluge/config:/config
      - /data/volume1/docker/deluge/downloads:/downloads
  radarr:
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    hostname: radarr
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/radarr/config:/config
      - /data/volume1/docker/deluge/downloads:/downloads
      - /data/volume1/movies:/movies
  sonarr:
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    hostname: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/sonarr/config:/config
      - /data/volume1/docker/deluge/downloads:/downloads
      - /data/volume1/tv:/tv
  prowlarr:
    container_name: Prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    hostname: prowlarr
    image: ghcr.io/linuxserver/prowlarr:develop
    ports:
      - 9696:9696/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/Prowlarr/config:/config
  mylar:
    container_name: mylar
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    hostname: mylar
    image: linuxserver/mylar3:latest
    ports:
      - 8090:8090/tcp
    restart: unless-stopped
    volumes:
      - /data/volume1/docker/mylar3/config:/config
      - /data/volume1/docker/deluge/downloads:/downloads
      - /data/volume1/comics:/comics
