version: "3"
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 81:81/tcp
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /data/volume1/docker/nginx-proxy/letsencrypt:/etc/letsencrypt
      - /data/volume1/docker/nginx-proxy/data:/data